package(default_visibility=["//visibility:public"])

cc_library(
    name = "base",
    srcs = ["base.cc"],
    hdrs = ["base.h"],
    deps = [
        "//solver/support:tick_executor",
        "@com_github_google_glog//:glog",
    ],
)
