package(default_visibility=["//visibility:public"])

cc_library(
    name = "trace_writer",
    srcs = ["trace_writer.cc"],
    hdrs = ["trace_writer.h"],
    deps = [
        "//solver/data:geometry",
        "@com_github_google_glog//:glog",
    ],
)
