package(default_visibility=["//visibility:public"])

cc_library(
    name = "model",
    srcs = ["model.cc"],
    hdrs = ["model.h"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
)

cc_library(
    name = "geometry",
    hdrs = ["geometry.h"],
)
