package(default_visibility=["//visibility:public"])

cc_library(
    name = "careless_controller",
    srcs = ["careless_controller.cc"],
    hdrs = ["careless_controller.h"],
    deps = [
        "//solver/data:geometry",
        "//solver/io:trace_writer",
        "@com_github_google_glog//:glog",
    ],
)
